# Generated by Django 4.2.26 on 2025-12-01 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='ai_summary',
        ),
        migrations.AddField(
            model_name='survey',
            name='foxhole_answer',
            field=models.TextField(blank=True, verbose_name='Who would you want in a foxhole with you?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='magic_answer',
            field=models.TextField(blank=True, verbose_name='If you had a magic wand, what would you change?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='respondent_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='respondent_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='respondent_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='survey',
            name='shadow_answer',
            field=models.TextField(blank=True, verbose_name='What is their shadow side?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
