# Generated by Django 4.2.26 on 2025-12-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_survey_ai_summary_survey_foxhole_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='relationship_context',
            field=models.TextField(blank=True, verbose_name='How do you know them?'),
        ),
    ]
