# Generated by Django 4.2.26 on 2025-12-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_survey_relationship_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='foxhole_answer',
            field=models.TextField(blank=True, verbose_name='Describe a situation where they were at their best. Why would you want them by your side in a crisis?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='magic_answer',
            field=models.TextField(blank=True, verbose_name='If you could magically grant them one improvement to help them grow, what would it be?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='shadow_answer',
            field=models.TextField(blank=True, verbose_name='What specific behaviors emerge when they are stressed, tired, or under pressure?'),
        ),
    ]
