# Generated by Django 4.2.26 on 2025-12-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_survey_foxhole_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='core_values',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='family_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stress_response',
            field=models.TextField(blank=True),
        ),
    ]
