# Generated by Django 4.2.26 on 2025-12-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_career_goal_profile_core_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='internal_anchor',
            field=models.TextField(blank=True, verbose_name='The Anchor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vision_anti_vision',
            field=models.TextField(blank=True, verbose_name='The Anti-Vision'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vision_perfect_tuesday',
            field=models.TextField(blank=True, verbose_name='The Perfect Tuesday in 2035'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vision_toast_test',
            field=models.TextField(blank=True, verbose_name='The Toast Test'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stress_response',
            field=models.TextField(blank=True, verbose_name='Pressure Reflex'),
        ),
    ]
