# Generated by Django 4.2.26 on 2025-12-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_internal_anchor_profile_vision_anti_vision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='foxhole_answer',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='magic_answer',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='shadow_answer',
        ),
        migrations.AddField(
            model_name='survey',
            name='energy_audit_answer',
            field=models.TextField(blank=True, verbose_name='The Energy Audit'),
        ),
        migrations.AddField(
            model_name='survey',
            name='future_self_answer',
            field=models.TextField(blank=True, verbose_name='The Future Self'),
        ),
        migrations.AddField(
            model_name='survey',
            name='glass_ceiling_answer',
            field=models.TextField(blank=True, verbose_name='The Glass Ceiling'),
        ),
        migrations.AddField(
            model_name='survey',
            name='stress_profile_answer',
            field=models.TextField(blank=True, verbose_name='The Stress Profile'),
        ),
    ]
