# Generated by Django 4.2.26 on 2025-12-04 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_survey_foxhole_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_link_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
