# Generated by Django 4.2.26 on 2025-12-04 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_survey_foxhole_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_link_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: [
                (setattr(row, 'public_link_uuid', uuid.uuid4()), row.save())
                for row in apps.get_model('core', 'Profile').objects.all()
            ],
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_link_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
