# Generated by Django 4.2.26 on 2025-12-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_surveyfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='final_thoughts',
            field=models.TextField(blank=True, verbose_name='Final Thoughts'),
        ),
        migrations.AddField(
            model_name='survey',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('friend', 'Friend'), ('family', 'Family'), ('coworker', 'Co-worker'), ('manager', 'Manager'), ('direct_report', 'Direct Report'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='respondent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='respondent_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
